import { captureJson, captureView, expect, test } from "./fixtures";
import { navigatePrimary } from "../e2e/fixtures";
import { openHistory } from "../e2e/perspective-helpers";
import { EPS_SUPPLY_RULE } from "../../src/lib/domain/eps-check";
import { LIFECYCLE_LABELS } from "../../src/lib/domain/lifecycle";
import { LIVE_CHECKS } from "./inventory";

test(LIVE_CHECKS.genericCorrection, async ({ page }, info) => {
  const id = "SYN-FQ123-TYPE2";
  await page.goto("/pharmacy");
  const flag = page.getByRole("banner").getByRole("switch");
  await expect(flag).not.toBeChecked();
  await page.getByRole("radio", { name: "Generic missing brand", exact: true }).check();
  await page.getByRole("textbox", { name: "Form dispensed", exact: true }).fill("");
  await page.getByRole("button", { name: "Send claim", exact: true }).click();
  await expect(page.getByRole("region", { name: "Submission receipt", exact: true })).toContainText(`${id}:2`);
  await page.getByRole("link", { name: "View submitted claim", exact: true }).click();
  const detail = page.getByRole("region", { name: "Claim detail", exact: true });
  const history = page.getByRole("region", { name: "Shared case history", exact: true });
  await expect(detail).toContainText(LIFECYCLE_LABELS.submitted.pharmacy);
  await history.getByRole("link", { name: "View NHSBSA case", exact: true }).click();
  await page.getByRole("button", { name: "Start review", exact: true }).click();
  await page.getByRole("radio", { name: /^Refer back / }).check();
  await page.getByRole("combobox", { name: "RB code (required)", exact: true }).selectOption("RB2B");
  await page.getByRole("textbox", { name: "Reason (required)", exact: true })
    .fill("Please confirm the missing presentation and brand or manufacturer dispensed.");
  await page.getByRole("button", { name: "Record decision", exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`/case/${id}/record$`));
  await page.getByRole("link", { name: "View pharmacy claim", exact: true }).click();
  await expect(detail).toContainText("RB2B");
  await expect(detail).toContainText(LIFECYCLE_LABELS.referred_back.pharmacy);
  await flag.setChecked(true);
  await openHistory(page);
  const attempts = history.getByRole("list", { name: "Immutable pharmacy attempts", exact: true }).locator(":scope > li");
  const originalAttempts = await attempts.allTextContents();
  expect(originalAttempts).toHaveLength(2);
  const fields = page.getByRole("group", { name: "Correct the EPS supply evidence", exact: true });
  const brand = fields.getByRole("textbox", { name: "Brand or manufacturer dispensed", exact: true });
  const pack = fields.getByRole("spinbutton", { name: "Pack size dispensed", exact: true });
  const form = fields.getByRole("textbox", { name: "Form dispensed", exact: true });
  await expect(brand).toHaveValue("");
  await expect(form).toHaveValue("");
  await page.getByRole("button", { name: "Re-check endorsement", exact: true }).click();
  await expect(detail).toContainText("Information may be missing");
  await brand.fill(EPS_SUPPLY_RULE.brandManufacturer);
  await pack.fill(String(EPS_SUPPLY_RULE.packSize));
  await form.fill(EPS_SUPPLY_RULE.form);
  await expect(detail).toContainText("Not checked for this edit");
  await expect(detail).toContainText(LIFECYCLE_LABELS.referred_back.pharmacy);
  expect(await attempts.allTextContents()).toEqual(originalAttempts);
  await page.getByRole("button", { name: "Re-check endorsement", exact: true }).click();
  await expect(detail).toContainText("Ready to resubmit");
  await page.getByRole("button", { name: "Resubmit claim", exact: true }).click();
  await expect(detail).toContainText(LIFECYCLE_LABELS.resubmitted.pharmacy);
  await expect(attempts).toHaveCount(3);
  expect((await attempts.allTextContents()).slice(0, 2)).toEqual(originalAttempts);
  await captureView(page, info, "generic-correction-awaiting-human-recheck");
  await history.getByRole("link", { name: "View NHSBSA case", exact: true }).click();
  await expect(page.getByRole("button", { name: "Record decision", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Start review", exact: true }).click();
  await expect(page.getByText("Sufficient: release to pricing once confirmed", { exact: true })).toBeVisible();
  await page.getByRole("radio", { name: /^Accept the recommendation \(as recommended\)/ }).check();
  await page.getByRole("textbox", { name: "Reason (required)", exact: true })
    .fill("Human recheck confirms the corrected brand, pack size and form.");
  await page.getByRole("button", { name: "Record decision", exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`/case/${id}/record$`));
  await navigatePrimary(page, "Pharmacy claims");
  await page.getByRole("group", { name: "Claim filters", exact: true }).getByRole("button", { name: /^Paid this month/ }).click();
  await page.getByRole("button", { name: `View ${id}`, exact: true }).click();
  await expect(detail).toContainText(LIFECYCLE_LABELS.paid.pharmacy);
  await openHistory(page);
  expect((await attempts.allTextContents()).slice(0, 2)).toEqual(originalAttempts);
  await expect(attempts).toHaveCount(3);
  const events = history.getByRole("list", { name: "Lifecycle events", exact: true });
  await expect(events.getByText("Human decision recorded (synthetic).", { exact: true })).toHaveCount(2);
  await expect(events).toContainText("RB2B");
  await captureView(page, info, "generic-correction-human-decided-paid");
  await captureJson(info, "generic-correction-immutable-history", { caseId: id, attempts: await attempts.allTextContents(), events: await events.innerText() });
});
